# Exercici 1

Agafa un conjunt de dades d'un tema que t'agradi i normalitza els atributs categòrics en dummy. Estandaritza els atributs numèrics amb StandardScaler.

In [30]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats

In [31]:
df = pd.read_csv("heart_2020.csv")
#source: https://www.kaggle.com/datasets/kamilpytlak/personal-key-indicators-of-heart-disease

In [32]:
df.head()

,Unnamed: 0,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,0,16.60,1,0,0,3.0,30.0,0,Female,55-59,White,1,1,Very good,5.0,1,0,1
1,1,0,20.34,0,0,1,0.0,0.0,0,Female,80 or older,White,0,1,Very good,7.0,0,0,0
2,2,0,26.58,1,0,0,20.0,30.0,0,Male,65-69,White,1,1,Fair,8.0,1,0,0
3,3,0,24.21,0,0,0,0.0,0.0,0,Female,75-79,White,0,0,Good,6.0,0,0,1
4,4,0,23.71,0,0,0,28.0,0.0,1,Female,40-44,White,0,1,Very good,8.0,0,0,0

In [33]:
df.shape

(319795, 19)

In [34]:
dummy = pd.get_dummies(data = df, columns =["Sex", "AgeCategory", "Race", "GenHealth"])

In [35]:
dummy.head()

,Unnamed: 0,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Diabetic,...,Race_Asian,Race_Black,Race_Hispanic,Race_Other,Race_White,GenHealth_Excellent,GenHealth_Fair,GenHealth_Good,GenHealth_Poor,GenHealth_Very good
0,0,0,16.60,1,0,0,3.0,30.0,0,1,...,0,0,0,0,1,0,0,0,0,1
1,1,0,20.34,0,0,1,0.0,0.0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,2,0,26.58,1,0,0,20.0,30.0,0,1,...,0,0,0,0,1,0,1,0,0,0
3,3,0,24.21,0,0,0,0.0,0.0,0,0,...,0,0,0,0,1,0,0,1,0,0
4,4,0,23.71,0,0,0,28.0,0.0,1,0,...,0,0,0,0,1,0,0,0,0,1

In [36]:
for col in dummy.columns:
    print(col)

Unnamed: 0
HeartDisease
BMI
Smoking
AlcoholDrinking
Stroke
PhysicalHealth
MentalHealth
DiffWalking
Diabetic
PhysicalActivity
SleepTime
Asthma
KidneyDisease
SkinCancer
Sex_Female
Sex_Male
AgeCategory_18-24
AgeCategory_25-29
AgeCategory_30-34
AgeCategory_35-39
AgeCategory_40-44
AgeCategory_45-49
AgeCategory_50-54
AgeCategory_55-59
AgeCategory_60-64
AgeCategory_65-69
AgeCategory_70-74
AgeCategory_75-79
AgeCategory_80 or older
Race_American Indian/Alaskan Native
Race_Asian
Race_Black
Race_Hispanic
Race_Other
Race_White
GenHealth_Excellent
GenHealth_Fair
GenHealth_Good
GenHealth_Poor
GenHealth_Very good

In [37]:
#dropping all non dummy columns in the new dataset
dummy = dummy.drop(columns = ["HeartDisease", "BMI", "Smoking", "AlcoholDrinking", "Stroke", "PhysicalHealth", "MentalHealth",
                     "DiffWalking", "Diabetic", "PhysicalActivity", "SleepTime", "Asthma", "KidneyDisease", "SkinCancer"])

In [38]:
#adding the dummies to the main dataset
df = pd.concat([df, dummy], axis = 1)

In [39]:
df.head()

,Unnamed: 0,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,...,Race_Asian,Race_Black,Race_Hispanic,Race_Other,Race_White,GenHealth_Excellent,GenHealth_Fair,GenHealth_Good,GenHealth_Poor,GenHealth_Very good
0,0,0,16.60,1,0,0,3.0,30.0,0,Female,...,0,0,0,0,1,0,0,0,0,1
1,1,0,20.34,0,0,1,0.0,0.0,0,Female,...,0,0,0,0,1,0,0,0,0,1
2,2,0,26.58,1,0,0,20.0,30.0,0,Male,...,0,0,0,0,1,0,1,0,0,0
3,3,0,24.21,0,0,0,0.0,0.0,0,Female,...,0,0,0,0,1,0,0,1,0,0
4,4,0,23.71,0,0,0,28.0,0.0,1,Female,...,0,0,0,0,1,0,0,0,0,1